server:
  port: 9009
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: API-GATEWAY
    cloud:
      #gateway:
        #discovery:
          #locator:
            #enabled: true
            #lower-case-service-id: true
      config:
        uri: http://localhost:8090



cloud:
  gateway:
    routes:
      - id: order-service
        #url:  http://localhost:8080/
        url:  lb://order-service/
        predicates:
          - Path:/order-service/**
        #filters:
          #- name: PreFilter
          #- name: PostFilter



      - id: payment-service
        #url: http://localhost:8081/
        url:  lb://payment-service/
        predicates:
          - Path:/payment-service/**

