server:
  port: 8090
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vijay-rathore93/config-server-repo
          search-paths: properties
          default-label: master
          username: vijay-rathore93
          password: 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



          # http://<host>:<port>/<file-name>/<profile>
          #if no profile then default


